# services that will NOT be present in your dev docker-compose.yml
redundant_services:
  - certbot
  - pgadmin
  - documentation
  - postgres_db
  - pgadmin
  - mongo_express
  - flask_server
  - node_server
  - scraper


service_details:
  service_config:
    repository: https://github.com/FIIT-TEAM8/service_config.git

  nginx:
    repository: https://github.com/FIIT-TEAM8/nginx_config
    clone_destination: service_config/data_link/nginx/
  
  es01:
    compose_adjustment:
      environment:
        - "discovery.type=single-node"
  
  # mongo_express:
  #   compose_adjustment:
  #     environment:
  #       - ME_CONFIG_SITE_BASEURL=/
