version: '3'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es01
    env_file:
      - local.env
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    volumes:
      - ./data/es_index:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          cpus: 2
   
  mongo_db:
    image: fiitteam8/mongo_db
    container_name: mongo_db
    env_file:
      - local.env
    volumes:
      - ./data/mongo_db:/data/db
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          cpus: 1

  mongo_express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - local.env
    deploy:
      resources:
        limits:
          cpus: 1


  postgres_db:
    image: fiitteam8/postgres_db
    container_name: postgres_db
    env_file:
      - local.env
    volumes:
      - ./data/postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: 1
  
  es_indexer:
   image: fiitteam8/es_indexer:latest
   container_name: es_indexer
   env_file:
     - local.env
     - remote.env
   depends_on:
     - mongo_db
     - es01
     - postgres_db
